apiVersion: v1
kind: Service
metadata:
  name: {{ include "predictor.fullname" . }}-api
spec:
  selector:
    app: {{ include "predictor.fullname" . }}-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.port }}