apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "predictor.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "predictor.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "predictor.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "predictor.fullname" . }}-api
            - secretRef:
                name: {{ .Values.api.secret.name | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10