{{- if .Values.api.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "predictor.fullname" . }}-api
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.api.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.api.secret.POSTGRES_PASSWORD | quote }}
{{- end }}