apiVersion: v1
kind: Service
metadata:
  name: {{ include "predictor.fullname" . }}-ui
spec:
  selector:
    app: {{ include "predictor.fullname" . }}-ui
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ui.containerPort }}